-- mysql

create table TB_ICR_CMA001M ( 
	MENU_ID VARCHAR(50) not null, 
	MENU_LVL_VL CHAR(1) not null, 
	MENU_NM VARCHAR(100) not null, 
	MENU_LNP_SQC INT(10) not null, 
	HGRN_MENU_ID VARCHAR(50) not null, 
	MENU_DSPL_YN CHAR(1) default 'N', 
	PPUP_YN CHAR(1) default 'N', 
	BSWR_DCD_VL VARCHAR(2) not null, 
	MENU_PATH_NM VARCHAR(100) not null, 
	USE_YN CHAR(1) default 'Y', 
	RPMS_FRRG_EMN CHAR(6) not null, 
	RPMS_FRRG_TS TIMESTAMP not null, 
	RPMS_LSMD_EMN CHAR(6) not null, 
	RPMS_LSMD_TS TIMESTAMP not null, 
	constraint PK_ICR_CMA001M primary key (MENU_ID) 
)

create table TB_ICR_CMA003M ( 
	EMN CHAR(6) NOT NULL, 
	EMM VARCHAR(50) NOT NULL,
	DVCD CHAR(4) NOT NULL, 
	BETEAM_CD CHAR(4) NOT NULL, 
	DUCD CHAR(4) NOT NULL, 
	JBCL_CD CHAR(1) NOT NULL, 
	JBTT_CD CHAR(4) NOT NULL, 
	JTM VARCHAR(50) NOT NULL, 
	PRAR_JBTT_NO CHAR(4) NOT NULL, 
	PRAR_JTM VARCHAR(50) NOT NULL, 
	ENCM_YMD VARCHAR(8) NOT NULL, 
	MVIN_YMD VARCHAR(8) NOT NULL, 
	DPLD_YN CHAR(1) DEFAULT 'N', 
	USE_YN CHAR(1) DEFAULT 'Y', 
	RPMS_FRRG_EMN CHAR(6) NOT NULL, 
	RPMS_FRRG_TS TIMESTAMP NOT NULL, 
	RPMS_LSMD_EMN CHAR(6) NOT NULL, 
	RPMS_LSMD_TS TIMESTAMP NOT NULL, 
	CONSTRAINT PK_ICR_CMA003M PRIMARY KEY (EMN) 
	)


create table TB_ICR_CMG101M ( 
	EMN CHAR(6) not null, 
	MENU_ID VARCHAR(50) not null, 
	MENU_LNP_SQC INT(10) not null, 
	USE_YN CHAR(1) default 'Y', 
	RPMS_FRRG_EMN CHAR(6) not null, 
	RPMS_FRRG_TS TIMESTAMP not null, 
	RPMS_LSMD_EMN CHAR(6) not null, 
	RPMS_LSMD_TS TIMESTAMP not null, 
	constraint PK_TB_ICR_CMG101M primary key (EMN, MENU_ID) 
)


create table TB_ICR_CMG102M ( 
	RSNB_APND_FILE_ID VARCHAR(20) not null, 
	ATCH_NO DECIMAL(22,0) not null, 
	RSNB_APND_FILE_DCD CHAR(2) not null, 
	ATCH_PATH_NM VARCHAR(100) not null, 
	TRTH_FILE_NM VARCHAR(100) not null, 
	ATCH_NM VARCHAR(300) not null, 
	ATCH_SIZE_VL INT(10) not null, 
	DEL_YN CHAR(1) default 'N', 
	RPMS_FRRG_EMN CHAR(6) not null, 
	RPMS_FRRG_TS TIMESTAMP not null, 
	RPMS_LSMD_EMN CHAR(6) not null, 
	RPMS_LSMD_TS TIMESTAMP not null, 
	constraint PK_ICR_CMG102M primary key (RSNB_APND_FILE_ID, ATCH_NO)
)


create table TB_ICR_CMG103M ( 
	CMCD_GRP_VL VARCHAR(20) not null, 
	CMGR_CD_NM VARCHAR(100) not null, 
	USE_YN CHAR(1) default 'Y', 
	RPMS_FRRG_EMN CHAR(6) not null, 
	RPMS_FRRG_TS TIMESTAMP not null, 
	RPMS_LSMD_EMN CHAR(6) not null, 
	RPMS_LSMD_TS TIMESTAMP not null, 
	constraint PK_ICR_CMG103M primary key (CMCD_GRP_VL) 
)


create table TB_ICR_CMG104M ( 
	PRRM_ID VARCHAR(50) not null, 
	PRRM_NM VARCHAR(100) not null, 
	PRRM_PATH_NM VARCHAR(200) not null, 
	PRRM_FILE_NM VARCHAR(100) not null, 
	PRRM_DESC_CON VARCHAR(4000) not null, 
	PPUP_YN CHAR(1) default 'N', 
	INNF_YN CHAR(1) not null, 
	USE_YN CHAR(1) default 'Y', 
	RPMS_FRRG_EMN CHAR(6) not null, 
	RPMS_FRRG_TS TIMESTAMP not null, 
	RPMS_LSMD_EMN CHAR(6) not null, 
	RPMS_LSMD_TS TIMESTAMP not null, 
	constraint PK_ICR_CMG104M primary key (PRRM_ID) 
)


create table TB_ICR_CMA004M ( 
	GRP_ID VARCHAR(10) not null, 
	GRP_NM VARCHAR(50) not null, 
	GRP_DESC_CON VARCHAR(500) not null, 
	GRP_MDFC_RGSN_TS TIMESTAMP(0) not null, 
	USE_YN CHAR(1) default 'Y', 
	RPMS_FRRG_EMN CHAR(6) not null, 
	RPMS_FRRG_TS TIMESTAMP not null, 
	RPMS_LSMD_EMN CHAR(6) not null, 
	RPMS_LSMD_TS TIMESTAMP not null, 
	constraint PK_ICR_CMA004M primary key (GRP_ID)
)

create table TB_ICR_CMA005M ( 
	GRP_ID VARCHAR(10) not null, 
	MENU_ID VARCHAR(50) not null, 
	USE_YN CHAR(1) default 'Y', 
	RPMS_FRRG_EMN CHAR(6) not null, 
	RPMS_FRRG_TS TIMESTAMP not null, 
	RPMS_LSMD_EMN CHAR(6) not null, 
	RPMS_LSMD_TS TIMESTAMP not null, 
	constraint PK_ICR_CMAOOSM primary key (GRP_ID, MENU_ID) 
)


create table TB_ICR_CMA006D ( 
	GRP_ID VARCHAR(10) NOT NULL, 
	EMN CHAR(6) NOT NULL, 
	IP_ADR VARCHAR(200) NOT NULL, 
	USE_YN CHAR(1) DEFAULT 'Y', 
	RPMS_FRRG_EMN CHAR(6) NOT NULL, 
	RPMS_FRRG_TS TIMESTAMP NOT NULL, 
	RPMS_LSMD_EMN CHAR(6) NOT NULL, 
	RPMS_LSMD_TS TIMESTAMP NOT NULL, 
	CONSTRAINT PK_ICR_CMA006D PRIMARY KEY (GRP_ID, EMN) 
)


create table TB_ICR_CMG105C ( 
	CMCD_GRP_VL VARCHAR(20) NOT NULL, 
	COM_CD CHAR(20) NOT NULL, 
	COM_CD_NM VARCHAR(100) NOT NULL, 
	CD_ABBR_NM VARCHAR(100) NOT NULL, 
	LNP_SQN INT(15) NOT NULL, 
	USE_YN CHAR(1) DEFAULT 'Y', 
	RPMS_FRRG_EMN CHAR(6) NOT NULL, 
	RPMS_FRRG_TS TIMESTAMP NOT NULL, 
	RPMS_LSMD_EMN CHAR(6) NOT NULL, 
	RPMS_LSMD_TS TIMESTAMP NOT NULL, 
	CONSTRAINT PK_ICR_CMG105C PRIMARY KEY (CMCD_GRP_VL, COM_CD)
)


create table TB_ICR_CMG106M ( 
	DVCD CHAR(4) not null, 
	DVM VARCHAR(50) not null, 
	OGZN_ATTCD CHAR(4) not null, 
	JRSD_HQCD CHAR(4) not null, 
	HGRN_BECD CHAR(4) not null, 
	CLSR_YMD VARCHAR(8) not null, 
	DPLD_EMN CHAR(6) not null, 
	DEPT_DCD CHAR(2) not null, 
	HGRN_DEPT_DSNC_CON VARCHAR(10) not null, 
	BRNC_BSOP_DCD CHAR(1) not null, 
	BRNC_SCD CHAR(1) not null, 
	ORZN_KCD CHAR(2) not null, 
	USE_YN CHAR(1) default 'Y', 
	RPMS_FRRG_EMN CHAR(6) not null, 
	RPMS_FRRG_TS TIMESTAMP not null, 
	RPMS_LSMD_EMN CHAR(6) not null, 
	RPMS_LSMD_TS TIMESTAMP not null, 
	constraint PK_ICR_CMG106M primary key (DVCD) 
)

-------------------------- 임 시 -------


create table TB_ICR_CMG106T ( 
	DVCD CHAR(4) not null, 
	DVM VARCHAR(50) not null, 
	OGZN_ATTCD CHAR(4) not null, 
	JRSD_HQCD CHAR(4) not null, 
	HGRN_BECD CHAR(4) not null, 
	CLSR_YMD VARCHAR(8) not null, 
	DPLD_EMN CHAR(6) not null, 
	DEPT_DCD CHAR(2) not null, 
	HGRN_DEPT_DSNC_CON VARCHAR(10) not null, 
	BRNC_BSOP_DCD CHAR(1) not null, 
	BRNC_SCD CHAR(1) not null, 
	ORZN_KCD CHAR(2) not null, 
	USE_YN CHAR(1) default 'Y', 
	RPMS_FRRG_EMN CHAR(6) not null, 
	RPMS_FRRG_TS TIMESTAMP not null, 
	RPMS_LSMD_EMN CHAR(6) not null, 
	RPMS_LSMD_TS TIMESTAMP not null, 
	constraint PK_ICR_CMG106T primary key (DVCD)
)

create table TB_ICR_CMG107L ( 
	SYS_PRHS_NO INT(22) NOT NULL, 
	OCRN_YMD VARCHAR(8) NOT NULL, 
	OCRN_HMS CHAR(6) NOT NULL, 
	EMN CHAR(6) NOT NULL, 
	EMP_IP VARCHAR(40) NOT NULL, 
	CLOT_URL_ADR VARCHAR(200) NOT NULL, 
	RQST_PARA_CON VARCHAR(4000) NOT NULL, 
	RQST_DTST_CON VARCHAR(4000) NOT NULL, 
	PCSN_TIM DECIMAL(10,3) NOT NULL, 
	PRHS_RSPN_CD CHAR(2) NOT NULL, 
	ERR_CON VARCHAR(2000) NOT NULL, 
	MENU_ID VARCHAR(50) NOT NULL, 
	USE_YN CHAR(1) DEFAULT 'Y', 
	RPMS_FRRG_EMN CHAR(6) NOT NULL, 
	RPMS_FRRG_TS TIMESTAMP NOT NULL, 
	RPMS_LSMD_EMN CHAR(6) NOT NULL, 
	RPMS_LSMD_TS TIMESTAMP NOT NULL, 
	CONSTRAINT PK_ICR_CMG107L PRIMARY KEY (SYS_PRHS_NO) 
)

create table TB_ICR_CMG109M ( 
	DVCD CHAR(4) NOT NULL, 
	BASE_YMD TIMESTAMP(0) NOT NULL, 
	DWK_DCD CHAR(1) NOT NULL, 
	BSDD_HLDD_YN CHAR(1) DEFAULT 'N', 
	HLDD_DCD CHAR(1) NOT NULL, 
	DD2_WLBR_YMD TIMESTAMP NOT NULL, 
	WLBR_YMD TIMESTAMP NOT NULL, 
	NXT_BSOP_YMD TIMESTAMP NOT NULL, 
	D2BAF_YMD TIMESTAMP NOT NULL, 
	RPMS_FRRG_EMN CHAR(6) NOT NULL, 
	RPMS_FRRG_TS TIMESTAMP NOT NULL, 
	RPMS_LSMD_EMN CHAR(6) NOT NULL, 
	RPMS_LSMD_TS TIMESTAMP NOT NULL, 
	CONSTRAINT PK_ICR_CMG109M PRIMARY KEY (DVCD, BASE_YMD) 
)


create table TB_ICR_CMG110M ( 
	RPMS_PBNS_SQN INT(5) not NULL, 
	RPMS_PBNS_TTL_NM VARCHAR(100) not null, 
	RPMS_PBNS_CON VARCHAR(2000) not null, 
	RPMS_PBNS_WRTN_EMN CHAR(6) not null, 
	RPMS_PBNS_MKR_NM VARCHAR(100) not null, 
	RPMS_PBNS_FRST_BLT_TS TIMESTAMP not null, 
	RPMS_PBNS_LAST_BLT_TS TIMESTAMP not null, 
	USE_YN CHAR(1) default 'Y', 
	RPMS_FRRG_EMN CHAR(6) not null, 
	RPMS_FRRG_TS TIMESTAMP not null, 
	RPMS_LSMD_EMN CHAR(6) not null, 
	RPMS_LSMD_TS TIMESTAMP not null, 
	constraint PK_ICR_CMG110M primary key (RPMS_PBNS_SQN) 
)

create table TB_ICR_ATC001L( 
	COTL_ACVT_TOB_YM CHAR(6) not null, 
	COTL_ACVT_TOB INT(5) not null, 
	MMBD_RSPT_DSNC_ID VARCHAR(10) not null, 
	MMBD_MNGM_ACVT_DSNC_ID VARCHAR(10) not null, 
	MNGM_ACVT_MNGN_CON TEXT not null, 
	MNGM_MNGN_LNP_SQN INT(5) not null, 
	MNGM_SCLT_SBJC_VL VARCHAR(2) not null, 
	RSNB_CHCP_RSLT_CD CHAR(2) not null, 
	CHCP_ITM_OPNN_CON TEXT not null, 
	RSNB_APND_FILE_ID VARCHAR(20) not null, 
	MMBD_DUM VARCHAR(50) not null,
	MMBD_EMN CHAR(6) not null, 
	MMBD_NM VARCHAR(50) not null, 
	MMBD_JTM VARCHAR(50) not null, 
	SNRT_YMD VARCHAR(8) not null, 
	RMVE_YMD VARCHAR(8) not null, 
	MMBD_CNPS_YN CHAR(1) default 'N', 
	MMBD_CNPS_SBJC_CON TEXT not null, 
	MMBD_RSNB_OVRV_CON TEXT not null, 
	MMBD_MNGM_OBLG_CON TEXT not null, 
	RSNB_SHR_YMD VARCHAR(8) not null, 
	MMBD_NFO_FTNT_CON VARCHAR(2000) not null, 
	MMBD_RSNB_FTNT_CON VARCHAR(2000) not null, 
	MMBD_MNGM_OBLG_FTNT_CON VARCHAR(2000) not null, 
	MMBD_CNBD_FTNT_CON VARCHAR(2000) not null, 
	USE_YN CHAR(1) default 'Y', 
	RPMS_FRRG_EMN CHAR(6) not null, 
	RPMS_FRRG_TS TIMESTAMP not null, 
	RPMS_LSMD_EMN CHAR(6) not null, 
	RPMS_LSMD_TS TIMESTAMP not null, 
	constraint PK_ICR_ATC001L primary key (COTL_ACVT_TOB_YM, COTL_ACVT_TOB, MMBD_RSPT_DSNC_ID, MMBD_MNGM_ACVT_DSNC_ID) 
	)

create table TB_ICR_ATC002L ( 
	COTL_ACVT_TOB_YM CHAR(6) not null, 
	COTL_ACVT_TOB INT(5) not null, 
	RSPT_DEPT_DSNC_ID VARCHAR(10) not null, 
	CMOP_CON VARCHAR(2000) not null, 
	USE_YN CHAR(1) default 'Y', 
	RPMS_FRRG_EMN CHAR(6) not null, 
	RPMS_FRRG_TS TIMESTAMP not null, 
	RPMS_LSMD_EMN CHAR(6) not null, 
	RPMS_LSMD_TS TIMESTAMP not null, 
	constraint PK_ICR_ATC002L primary key (COTL_ACVT_TOB_YM, COTL_ACVT_TOB, RSPT_DEPT_DSNC_ID) 
	)


create table TB_ICR_ATC003L ( 
	COTL_ACVT_TOB_YM CHAR(6) not null, 
	COTL_ACVT_TOB INT(5) not null, 
	DVCD CHAR(4) not null, 
	MNGM_ACVT_DSNC_ID VARCHAR(10) not null, 
	MNGM_ACVT_DTLS_CD CHAR(2) not null, 
	MNGM_ACVT_CON TEXT not null, 
	MNGM_ACVT_DTLS_CON TEXT not null, 
	DEPT_RSPB_BSWR_NM TEXT not null, 
	DEPT_JRSC_INSD_RGLN_CON TEXT not null, 
	MNGM_ACVT_DSNC_SQN INT(5) not null, 
	EFTT_CYL_CD CHAR(2) not null, 
	RMRK_CON VARCHAR(2000) not null, 
	RSNB_APND_FILE_ID VARCHAR(20) not null, 
	ECTG_YN CHAR(1) default 'N', 
	ECTG_RSN_CON TEXT not null, 
	DEPT_RSNB_OVRV_CON TEXT not null, 
	RSNB_CHCP_ITM_CON TEXT not null, 
	CHCP_GIDE_CON TEXT not null, 
	MNGM_SCLT_SBJC_VL VARCHAR(2) not null, 
	RSNB_CHCP_RSLT_CD CHAR(2) not null, 
	CHCP_ITM_OPNN_CON TEXT not null, 
	MMBD_RSPT_DSNC_ID VARCHAR(10) not null, 
	MMBD_DUM VARCHAR(50) not null, 
	MMBD_EMN CHAR(6) not null, 
	MMBD_NM VARCHAR(50) not null, 
	MMBD_OPNN_CON TEXT not null, 
	MMBD_OPNN_WRTN_TS TIMESTAMP not null, 
	DRHQ_EMN CHAR(6) not null, 
	DRHQ_NM VARCHAR(100) not null, 
	DRHQ_OPNN_CON TEXT not null, 
	DRHQ_OPNN_WRTN_TS TIMESTAMP not null, 
	WRPX_EMN CHAR(6) not null, 
	WRPX_EMM VARCHAR(50) not null, 
	LRRN_DPLD_EMN CHAR(6) not null, 
	LRRN_DPLD_EMM VARCHAR(50) not null, 
	DPLD_EMN CHAR(6) not null, 
	DPLD_NM VARCHAR(100) not null, 
	IPCT_EMN CHAR(6) not null, 
	IPCT_NM VARCHAR(100) not null, 
	IPCT_OPNN_CON TEXT not null, 
	IPCT_OPNN_WRTN_TS TIMESTAMP not null, 
	RSNB_CHCP_RGSN_SCD CHAR(2) not null, 
	RSNB_PGRS_SCD CHAR(2) not null, 
	DVM VARCHAR(50) not null, 
	MMBD_MNGM_ACVT_RLTN_CON VARCHAR(2000) not null, 
	USE_YN CHAR(1) default 'Y', 
	RPMS_FRRG_EMN CHAR(6) not null, 
	RPMS_FRRG_TS TIMESTAMP not null, 
	RPMS_LSMD_EMN CHAR(6) not null, 
	RPMS_LSMD_TS TIMESTAMP not null, 
	constraint PK_ICR_ATC003L primary key (COTL_ACVT_TOB_YM, COTL_ACVT_TOB, DVCD, MNGM_ACVT_DSNC_ID, MNGM_ACVT_DTLS_CD)
	)

create table TB_ICR_ATC006L ( 
	COTL_ACVT_TOB_YM CHAR(6) not null, 
	COTL_ACVT_TOB INT(5) not null, 
	MNGM_ACVT_DSNC_ID VARCHAR(10) not null, 
	MNGM_ACVT_DTLS_CD CHAR(2) not null, 
	COTL_SYST_SQN INT(5) not null, 
	COTL_SYST_CON VARCHAR(4000) not null, 
	COTL_SYST_GIDE_CON VARCHAR(4000) not null, 
	SCLT_YN CHAR(1) default 'N', 
	USE_YN CHAR(1) not null, 
	RPMS_FRRG_EMN CHAR(6) not null, 
	RPMS_FRRG_TS TIMESTAMP not null, 
	RPMS_LSMD_EMN CHAR(6) not null, 
	RPMS_LSMD_TS TIMESTAMP not null, 
	constraint PK_ICR_ATC006L primary key (COTL_ACVT_TOB_YM, COTL_ACVT_TOB, MNGM_ACVT_DSNC_ID, MNGM_ACVT_DTLS_CD, COTL_SYST_SQN)
)

create table TB_ICR_ATI101L ( 
	COTL_ACVT_TOB_YM CHAR(6) NOT NULL, 
	COTL_ACVT_TOB INT(5) NOT NULL, 
	DVCD CHAR(4) NOT NULL, 
	MNGM_ACVT_DSNC_ID VARCHAR(10) NOT NULL, 
	RSNB_CHCP_RSLT_CON TEXT NOT NULL, 
	RSNB_PGRS_SCD CHAR(2) NOT NULL, 
	IMPV_ENHN_CHCP_GIDE_CON TEXT NOT NULL, 
	IMPV_ENHN_CHCP_ITM_CON TEXT NOT NULL, 
	RSNB_MPV_PLAN_CON TEXT NOT NULL, 
	IMPV_PLAN_WRTN_YMD VARCHAR(8) NOT NULL, 
	RSNB_IMPV_FNSG_SCDL_YMD VARCHAR(8) NOT NULL, 
	TMS2_APND_FILE_ID VARCHAR(20) NOT NULL, 
	IMPV_RSLT_CON TEXT NOT NULL, 
	IMPV_RSLT_WRTN_YMD VARCHAR(8) NOT NULL, 
	TMS1_APND_FILE_ID VARCHAR(20) NOT NULL, 
	IMPV_FNSG_YMD VARCHAR(8) NOT NULL, 
	WRTN_TS TIMESTAMP(0) NOT NULL, 
	MKR_EMN CHAR(6) NOT NULL, 
	MKR_NM VARCHAR(35) NOT NULL, 
	DRHQ_PLAN_CON TEXT NOT NULL, 
	DRHQ_PLAN_WRTN_TS TIMESTAMP NOT NULL, 
	DRHQ_PLAN_MKR_EMN CHAR(6) NOT NULL, 
	DRHQ_PLAN_MKR_NM VARCHAR(50) NOT NULL, 
	DRHQ_RSLT_CON TEXT NOT NULL, 
	DRHQ_RSLT_WRTN_TS TIMESTAMP NOT NULL, 
	DRHQ_RSLT_MKR_EMN CHAR(6) NOT NULL, 
	DRHQ_RSLT_MKR_NM VARCHAR(50) NOT NULL, 
	MMBD_PLAN_CON TEXT NOT NULL, 
	MMBD_PLAN_WRTN_TS TIMESTAMP NOT NULL, 
	MMBD_PLAN_MKR_EMN CHAR(6) NOT NULL, 
	MMBD_PLAN_MKR_NM VARCHAR(50) NOT NULL, 
	MMBD_RSLT_CON TEXT NOT NULL, 
	MMBD_RSLT_WRTN_TS TIMESTAMP NOT NULL, 
	MMBD_RSLT_MKR_EMN CHAR(6) NOT NULL, 
	MMBD_RSLT_MKR_NM VARCHAR(50) NOT NULL, 
	USE_YN CHAR(1) DEFAULT 'Y', 
	RPMS_FRRG_EMN CHAR(6) NOT NULL, 
	RPMS_FRRG_TS TIMESTAMP NOT NULL, 
	RPMS_LSMD_EMN CHAR(6) NOT NULL, 
	RPMS_LSMD_TS TIMESTAMP NOT NULL, 
	CONSTRAINT PK_ICR_AT1101L PRIMARY KEY (COTL_ACVT_TOB_YM, COTL_ACVT_TOB, DVCD, MNGM_ACVT_DSNC_ID) 
)

create table TB_ICR_ATC004T ( 
	COTL_ACVT_TOB_YM CHAR(6) not null, 
	COTL_ACVT_TOB INT(5) not null, 
	DVCD CHAR(4) not null, 
	DEPT_RSPB_BSWR_DSNC_ID VARCHAR(10) not null, 
	MNGM_ACVT_DSNC_ID VARCHAR(10) not null, 
	DEPT_RSPB_BSWR_NM VARCHAR(2000) not null, 
	DEPT_JRSC_INSD_RGLN_CON TEXT not null, 
	MNGM_ACVT_DSNC_SQN INT(5) not null, 
	MNGM_ACVT_CON TEXT not null, 
	MNGM_ACVT_DTLS_CON TEXT not null, 
	EFTT_CYL_CD CHAR(2) not null, 
	MMBD_RSPT_DSNC_ID VARCHAR(10) not null, 
	ECTG_YN CHAR(1) default 'N', 
	ECTG_RSN_CON TEXT not null, 
	USE_YN CHAR(1) default 'Y', 
	RPMS_FRRG_EMN CHAR(6) not null, 
	RPMS_FRRG_TS TIMESTAMP not null, 
	RPMS_LSMD_EMN CHAR(6) not null, 
	RPMS_LSMD_TS TIMESTAMP not null, 
	constraint PK_ICR_ATC004T primary key (COTL_ACVT_TOB_YM, COTL_ACVT_TOB, DVCD, DEPT_RSPB_BSWR_DSNC_ID, MNGM_ACVT_DSNC_ID)
)

create table TB_ICR_ATC005L ( 
	COTL_ACVT_TOB_YM CHAR(6) not null, 
	COTL_ACVT_TOB INT(5) not null, 
	COTL_ACVT_TOB_NM VARCHAR(100) not null, 
	TOB_DFNN_TS TIMESTAMP not null, 
	LAST_ITM_CRET_TS TIMESTAMP not null, 
	USE_YN CHAR(1) default 'Y', 
	RPMS_FRRG_EMN CHAR(6) not null, 
	RPMS_FRRG_TS TIMESTAMP not null, 
	RPMS_LSMD_EMN CHAR(6) not null, 
	RPMS_LSMD_TS TIMESTAMP not null, 
	constraint PK_ICR_ATC005L primary key (COTL_ACVT_TOB_YM, COTL_ACVT_TOB)
)

create table TB_ICR_ATI002L ( 
	RGSN_YMD CHAR(8) NOT NULL, 
	RTN VARCHAR(10) NOT NULL, 
	SSTM_OVRV_NM VARCHAR(200) NOT NULL, 
	SSTM_OVRV_CON VARCHAR(4000) NOT NULL, 
	RGSR_EMN CHAR(6) NOT NULL, 
	RGSR_NM VARCHAR(30) NOT NULL, 
	RGSR_DVCD CHAR(4) NOT NULL, 
	PBNT_SBJC_YN CHAR(1) DEFAULT 'N', 
	RSNB_APND_FILE_ID VARCHAR(20) NOT NULL, 
	USE_YN CHAR(1) DEFAULT 'Y', 
	RPMS_FRRG_EMN CHAR(6) NOT NULL, 
	RPMS_FRRG_TS TIMESTAMP NOT NULL, 
	RPMS_LSMD_EMN CHAR(6) NOT NULL, 
	RPMS_LSMD_TS TIMESTAMP NOT NULL, 
	CONSTRAINT PK_ICR_AT1002L PRIMARY KEY (RGSN_YMD, RTN)
)

create table TB_ICR_ATI003L (
	RTN VARCHAR(10) NOT NULL, 
	RGSN_YMD VARCHAR(8) NOT NULL, 
	EDCT_ACVT_NM VARCHAR(500) NOT NULL, 
	EDCT_ACVT_CON VARCHAR(4000) NOT NULL, 
	EDCT_TGPS_NM VARCHAR(50) NOT NULL, 
	EDCT_STTG_TS TIMESTAMP NOT NULL, 
	EDCT_FNSH_TS TIMESTAMP NOT NULL, 
	RGSR_EMN CHAR(6) NOT NULL, 
	RGSR_NM VARCHAR(30) NOT NULL, 
	RGSR_DVCD CHAR(4) NOT NULL, 
	RSNB_APND_FILE_ID VARCHAR(20) NOT NULL, 
	USE_YN CHAR(1) DEFAULT 'Y', 
	RPMS_FRRG_EMN CHAR(6) NOT NULL, 
	RPMS_FRRG_TS TIMESTAMP NOT NULL, 
	RPMS_LSMD_EMN CHAR(6) NOT NULL, 
	RPMS_LSMD_TS TIMESTAMP NOT NULL, 
	CONSTRAINT PK_ICR_AT1003L PRIMARY KEY (RTN, RGSN_YMD) 
)

create table TB_ICR_ATI004L ( 
	RTN VARCHAR(10) NOT NULL, 
	RGSN_YMD CHAR(8) NOT NULL, 
	DVCD CHAR(4) NOT NULL, 
	JBTT_CD CHAR(4) NOT NULL, 
	INDT_EMN CHAR(6) NOT NULL, 
	INDT_EMM VARCHAR(50) NOT NULL, 
	IMPV_ENHN_NM VARCHAR(100) NOT NULL, 
	IMPV_ENHN_CON VARCHAR(4000) NOT NULL, 
	RGSR_EMN CHAR(6) NOT NULL, 
	RGSR_NM VARCHAR(30) NOT NULL, 
	IMPV_TGT_GRP_DSNC_CON VARCHAR(10) NOT NULL, 
	IMPV_TGT_TMS1_DTLS_DSNC_CON VARCHAR(10) NOT NULL, 
	IMPV_TGT_TMS2_DTLS_DSNC_CON VARCHAR(10) NOT NULL, 
	IMPV_ENHN_CHCP_GIDE_CON VARCHAR(4000) NOT NULL, 
	IMPV_ENHN_CHCP_ITM_CON VARCHAR(4000) NOT NULL, 
	USE_YN CHAR(1) DEFAULT 'Y', 
	RPMS_FRRG_EMN CHAR(6) NOT NULL, 
	RPMS_FRRG_TS TIMESTAMP NOT NULL, 
	RPMS_LSMD_EMN CHAR(6) NOT NULL, 
	RPMS_LSMD_TS TIMESTAMP NOT NULL, 
	CONSTRAINT PK_ICR_ATI004L PRIMARY KEY (RTN, RGSN_YMD)
)

create table TB_ICR_LDP101M ( 
	DVCD CHAR(4) not null, 
	DVM VARCHAR(50) not null, 
	DPLD_DUM VARCHAR(50) not null, 
	DPLD_JTM VARCHAR(50) not null, 
	DEPT_RSNB_OVRV_CON VARCHAR(4000) not null, 
	DEPT_RSNB_RLTN_ALW_CON VARCHAR(4000) not null, 
	USE_YN CHAR(1) default 'Y', 
	RPMS_FRRG_EMN CHAR(6) not null, 
	RPMS_FRRG_TS TIMESTAMP not null, 
	RPMS_LSMD_EMN CHAR(6) not null, 
	RPMS_LSMD_TS TIMESTAMP not null, 
	constraint PK_ICR_LDP101M primary key (DVCD) 
)


create table TB_ICR_LDP102M ( 
	DEPT_RSPB_BSWR_DSNC_ID VARCHAR(10) not null, 
	DVCD CHAR(4) not null, 
	RSNB_BETEAM_NM VARCHAR(500) not null, 
	DEPT_RSPB_BSWR_NM VARCHAR(2000) not null, 
	RSGR_CD CHAR(2) not null, 
	COTL_LEVL_LVL_VL CHAR(1) not null, 
	USE_YN CHAR(1) not null, 
	RPMS_FRRG_EMN CHAR(6) not null, 
	RPMS_FRRG_TS TIMESTAMP not null, 
	RPMS_LSMD_EMN CHAR(6) not null, 
	RPMS_LSMD_TS TIMESTAMP not null, 
	constraint PK_ICR_LDP102M primary key (DEPT_RSPB_BSWR_DSNC_ID)
)

create table TB_ICR_LDP103R ( 
	DEPT_RSPB_BSWR_DSNC_ID VARCHAR(10) NOT NULL, 
	MNGM_ACVT_DSNC_ID VARCHAR(10) NOT NULL, 
	DVCD CHAR(4) NOT NULL, 
	USE_YN CHAR(1) NOT NULL, 
	RPMS_FRRG_EMN CHAR(6) NOT NULL, 
	RPMS_FRRG_TS TIMESTAMP NOT NULL, 
	RPMS_LSMD_EMN CHAR(6) NOT NULL, 
	RPMS_LSMD_TS TIMESTAMP NOT NULL, 
	CONSTRAINT PK_ICR_LDP103R PRIMARY KEY (DEPT_RSPB_BSWR_DSNC_ID, MNGM_ACVT_DSNC_ID, DVCD)
)

create table TB_ICR_LDP104M ( 
	MNGM_ACVT_DSNC_ID VARCHAR(10) NOT NULL, 
	MNGM_ACVT_DSNC_SQN INT(5) NOT NULL, 
	MNGM_ACVT_CON VARCHAR(4000) NOT NULL, 
	MNGM_ACVT_DTLS_CON VARCHAR(4000) NOT NULL, 
	DVCD CHAR(4) NOT NULL, 
	EFTT_CYL_CD CHAR(2) NOT NULL, 
	RMRK_CON VARCHAR(2000) NOT NULL, 
	MNGM_ACVT_SNCT_SCD CHAR(2) NOT NULL, 
	MNGM_ACVT_SNCT_RQPS_EMN CHAR(6) NOT NULL, 
	MNGM_ACVT_SNCT_RQST_TS TIMESTAMP NOT NULL, 
	MNGM_ACVT_TMS1_SNPN_EMN CHAR(6) NOT NULL, 
	MNGM_ACVT_TMS1_SNCT_TS TIMESTAMP NOT NULL, 
	MNGM_ACVT_TMS2_SNPN_EMN CHAR(6) NOT NULL, 
	MNGM_ACVT_TMS2_SNCT_TS TIMESTAMP NOT NULL, 
	USE_YN CHAR(1) NOT NULL, 
	RPMS_FRRG_EMN CHAR(6) NOT NULL, 
	RPMS_FRRG_TS TIMESTAMP NOT NULL, 
	RPMS_LSMD_EMN CHAR(6) NOT NULL, 
	RPMS_LSMD_TS TIMESTAMP NOT NULL, 
	CONSTRAINT PK_ICR_LDP104M PRIMARY KEY (MNGM_ACVT_DSNC_ID)
)

create table TB_ICR_LDP105M ( 
	MNGM_ACVT_DSNC_ID VARCHAR(10) not null, 
	MNGM_ACVT_DTLS_CD CHAR(2) not null,
	RSNB_CHCP_ITM_CON VARCHAR(4000) not null, 
	CHCP_GIDE_CON VARCHAR(4000) not null, 
	MNGM_SCLT_SBJC_VL VARCHAR(2) not null, 
	USE_YN CHAR(1) not null, 
	RPMS_FRRG_EMN CHAR(6) not null, 
	RPMS_FRRG_TS TIMESTAMP not null, 
	RPMS_LSMD_EMN CHAR(6) not null, 
	RPMS_LSMD_TS TIMESTAMP not null, 
	constraint PK_ICR_LDP105M primary key (MNGM_ACVT_DSNC_ID, MNGM_ACVT_DTLS_CD)
)

create table TB_ICR_LDP106M ( 
	MNGM_ACVT_DSNC_ID VARCHAR(10) not null, 
	MNGM_ACVT_DTLS_CD CHAR(2) not null, 
	COTL_SYST_SQN INT(5) not null, 
	COTL_SYST_CON VARCHAR(4000) not null, 
	COTL_SYST_GIDE_CON VARCHAR(4000) not null, 
	USE_YN CHAR(1) not null, 
	RPMS_FRRG_EMN CHAR(6) not null, 
	RPMS_FRRG_TS TIMESTAMP not null, 
	RPMS_LSMD_EMN CHAR(6) not null, 
	RPMS_LSMD_TS TIMESTAMP not null, 
	constraint PK_ICR_LDP106M primary key (MNGM_ACVT_DSNC_ID, MNGM_ACVT_DTLS_CD, COTL_SYST_SQN)
)

create table TB_ICR_LDP107H ( 
	MNGM_ACVT_DSNC_ID VARCHAR(10) NOT NULL, 
	PRHS_SQN INT(5) NOT NULL, 
	MNGM_ACVT_DSNC_SQN INT(5) NOT NULL, 
	MNGM_ACVT_CON VARCHAR(4000) NOT NULL, 
	MNGM_ACVT_DTLS_CON VARCHAR(4000) NOT NULL, 
	DVCD CHAR(4) NOT NULL, 
	EFTT_CYL_CD CHAR(2) NOT NULL, 
	EFTT_CYL_DSNC_CON VARCHAR(10) NOT NULL, 
	RSPB_BSWR_CON VARCHAR(500) NOT NULL, 
	RMRK_CON VARCHAR(2000) NOT NULL, 
	STTS_NM VARCHAR(30) NOT NULL, 
	USE_YN CHAR(1) NOT NULL, 
	RPMS_FRRG_EMN CHAR(6) NOT NULL, 
	RPMS_FRRG_TS TIMESTAMP NOT NULL, 
	RPMS_LSMD_EMN CHAR(6) NOT NULL, 
	RPMS_LSMD_TS TIMESTAMP NOT NULL, 
	CONSTRAINT PK_ICR_LDP104H PRIMARY KEY (MNGM_ACVT_DSNC_ID, PRHS_SQN)
)

create table TB_ICR_LDP108M ( 
	DVCD CHAR(4) not null, 
	MNGM_ACVT_DSNC_ID VARCHAR(10) not null, 
	LRRN_DPLD_EMN CHAR(6) not null, 
	LRRN_DPLD_EMM VARCHAR(50) not null, 
	DPLD_EMN CHAR(6) not null, 
	DPLD_NM VARCHAR(100) not null, 
	DRHQ_EMN CHAR(6) not null, 
	DRHQ_NM VARCHAR(100) not null, 
	MMBD_RSPT_DSNC_ID VARCHAR(10) not null, 
	MMBD_DUM VARCHAR(50) not null, 
	MMBD_EMN CHAR(6) not null, 
	MMBD_NM VARCHAR(50) not null, 
	USE_YN CHAR(1) default 'Y', 
	RPMS_FRRG_EMN CHAR(6) not null, 
	RPMS_FRRG_TS TIMESTAMP not null, 
	RPMS_LSMD_EMN CHAR(6) not null, 
	RPMS_LSMD_TS TIMESTAMP not null, 
	constraint PK_ICR_LDP108M primary key (DVCD, MNGM_ACVT_DSNC_ID)
)


create table TB_ICR_LDD001M ( 
	MMBD_RSPT_DSNC_ID VARCHAR(10) not null, 
	MMBD_DUM VARCHAR(50) not null, 
	MMBD_EMN CHAR(6) not null, 
	MMBD_NM VARCHAR(50) not null, 
	MMBD_JTM VARCHAR(50) not null, 
	SNRT_YMD VARCHAR(8) not null, 
	RMVE_YMD VARCHAR(8) not null, 
	MMBD_CNPS_YN CHAR(1) default 'N',
	MMBD_CNPS_SBJC_CON VARCHAR(4000) not null, 
	MMBD_RSNB_OVRV_CON VARCHAR(4000) not null, 
	MMBD_MNGM_OBLG_CON TEXT not null, 
	RSNB_SHR_YMD VARCHAR(8) not null, 
	MMBD_INFO_FTNT_CON VARCHAR(2000) not null, 
	MMBD_RSNB_FTNT_CON VARCHAR(2000) not null, 
	MMBD_MNGM_OBLG_FTNT_CON VARCHAR(2000) not null, 
	MMBD_CNBD_FTNT_CON VARCHAR(2000) not null, 
	USE_YN CHAR(1) default 'Y', 
	RPMS_FRRG_EMN CHAR(6) not null, 
	RPMS_FRRG_TS TIMESTAMP not null, 
	RPMS_LSMD_EMN CHAR(6) not null, 
	RPMS_LSMD_TS TIMESTAMP not null, 
	constraint PK_ICR_LDD001M primary key (MMBD_RSPT_DSNC_ID)
)


create table TB_ICR_LDD002H ( 
	MMBD_RSPT_DSNC_ID VARCHAR(10) not null, 
	PRHS_SQN INT(5) not null, 
	MMBD_DUM VARCHAR(50) not null, 
	MMBD_EMN CHAR(6) not null, 
	MMBD_NM VARCHAR(50) not null, 
	MMBD_JTM VARCHAR(50) not null, 
	SNRT_YMD VARCHAR(8) not null, 
	RMVE_YMD VARCHAR(8) not null, 
	MMBD_CNPS_YN CHAR(1) default 'N', 
	MMBD_CNPS_SBJC_CON VARCHAR(4000) not null, 
	MMBD_RSNB_OVRV_CON VARCHAR(4000) not null, 
	MMBD_MNGM_OBLG_CON TEXT not null, 
	RSNB_SHR_YMD VARCHAR(8) not null, 
	AFM_MMBD_EMN CHAR(6) not null, 
	AFM_MMBD_EMM VARCHAR(50) not null, 
	STTS_NM VARCHAR(30) not null, 
	USE_YN CHAR(1) default 'Y', 
	RPMS_FRRG_EMN CHAR(6) not null, 
	RPMS_FRRG_TS TIMESTAMP not null, 
	RPMS_LSMD_EMN CHAR(6) not null, 
	RPMS_LSMD_TS TIMESTAMP not null, 
	constraint PK_ICR_LDD001H primary key (MMBD_RSPT_DSNC_ID, PRHS_SQN)
)


create table TB_ICR_LDD003R ( 
	MMBD_RSPT_DSNC_ID VARCHAR(10) not null, 
	DVCD CHAR(4) not null, 
	USE_YN CHAR(1) default 'Y', 
	RPMS_FRRG_EMN CHAR(6) not null, 
	RPMS_FRRG_TS TIMESTAMP not null, 
	RPMS_LSMD_EMN CHAR(6) not null, 
	RPMS_LSMD_TS TIMESTAMP not null, 
	constraint PK_ICR_LDD003R primary key (MMBD_RSPT_DSNC_ID, DVCD)
)

create table TB_ICR_LDD004R ( 
	MMBD_RSNB_DTL_DSNC_ID VARCHAR(10) not null, 
	DEPT_RSPB_BSWR_DSNC_ID VARCHAR(10) not null, 
	DEPT_JRSC_INSD_RGLN_CON VARCHAR(4000) not null, 
	MMBD_RSNB_DTL_PRTL_CON VARCHAR(4000) not null, 
	USE_YN CHAR(1) not null, 
	RPMS_FRRG_EMN CHAR(6) not null, 
	RPMS_FRRG_TS TIMESTAMP not null, 
	RPMS_LSMD_EMN CHAR(6) not null, 
	RPMS_LSMD_TS TIMESTAMP not null, 
	constraint PK_ICR_LDD004R primary key (MMBD_RSNB_DTL_DSNC_ID, DEPT_RSPB_BSWR_DSNC_ID)
)

create table TB_ICR_LDD005R ( 
	MMBD_RSPT_DSNC_ID VARCHAR(10) NOT NULL, 
	CNBD_DSNC_ID VARCHAR(10) NOT NULL, 
	CNBD_RSPT_CD CHAR(2) NOT NULL, 
	USE_YN CHAR(1) DEFAULT 'Y', 
	RPMS_FRRG_EMN CHAR(6) NOT NULL, 
	RPMS_FRRG_TS TIMESTAMP NOT NULL, 
	RPMS_LSMD_EMN CHAR(6) NOT NULL, 
	RPMS_LSMD_TS TIMESTAMP NOT NULL, 
	CONSTRAINT PK_ICR_LDD005R primary key (MMBD_RSPT_DSNC_ID, CNBD_DSNC_ID)
)

create table TB_ICR_LDD006R ( 
	MMBD_RSPT_DSNC_ID VARCHAR(10) NOT NULL, 
	MMBD_RSNB_DSNC_ID VARCHAR(10) NOT NULL, 
	USE_YN CHAR(1) DEFAULT 'Y', 
	RPMS_FRRG_EMN CHAR(6) NOT NULL, 
	RPMS_FRRG_TS TIMESTAMP NOT NULL, 
	RPMS_LSMD_EMN CHAR(6) NOT NULL, 
	RPMS_LSMD_TS TIMESTAMP NOT NULL, 
	CONSTRAINT PK_ICR_LDD006R PRIMARY KEY (MMBD_RSPT_DSNC_ID, MMBD_RSNB_DSNC_ID)
)

create table TB_ICR_LDD007M ( 
	MMBD_RSNB_DSNC_ID VARCHAR(10) NOT NULL, 
	MMBD_RSNB_CON VARCHAR(4000) NOT NULL, 
	USE_YN CHAR(1) NOT NULL, 
	RPMS_FRRG_EMN CHAR(6) NOT NULL,
	RPMS_FRRG_TS TIMESTAMP NOT NULL,
	RPMS_LSMD_EMN CHAR(6) NOT NULL, 
	RPMS_LSMD_TS TIMESTAMP NOT NULL, 
	CONSTRAINT PK_ICR_LDD007M PRIMARY KEY (MMBD_RSNB_DSNC_ID)
)

create table TB_ICR_LDD008M ( 
	MMBD_RSNB_DTL_DSNC_ID VARCHAR(10) NOT NULL, 
	MMBD_RSNB_DTL_CON VARCHAR(4000) NOT NULL, 
	RLTD_ALW_TRL_CON VARCHAR(4000) NOT NULL, 
	USE_YN CHAR(1) NOT NULL, 
	RPMS_FRRG_EMN CHAR(6) NOT NULL, 
	RPMS_FRRG_TS TIMESTAMP NOT NULL, 
	RPMS_LSMD_EMN CHAR(6) NOT NULL, 
	RPMS_LSMD_TS TIMESTAMP NOT NULL, 
	CONSTRAINT PK_ICR_LDD008M PRIMARY KEY (MMBD_RSNB_DTL_DSNC_ID) 
)


create table TB_ICR_LDD009R ( 
	MMBD_RSNB_DSNC_ID VARCHAR(10) NOT NULL, 
	MMBD_RSNB_DTL_DSNC_ID VARCHAR(10) NOT NULL, 
	USE_YN CHAR(1) NOT NULL, 
	RPMS_FRRG_EMN CHAR(6) NOT NULL, 
	RPMS_FRRG_TS TIMESTAMP NOT NULL, 
	RPMS_LSMD_EMN CHAR(6) NOT NULL, 
	RPMS_LSMD_TS TIMESTAMP NOT NULL, 
	CONSTRAINT PK_ICR_LDD009R PRIMARY KEY (MMBD_RSNB_DSNC_ID, MMBD_RSNB_DTL_DSNC_ID) 
)


create table TB_ICR_LDD010M ( 
	CNBD_DSNC_ID VARCHAR(10) NOT NULL, 
	CNBD_NM VARCHAR(50) NOT NULL, 
	CNBD_HLD_CYL_CD CHAR(2) NOT NULL, 
	PRMR_DLBT_DCDE_SBJC_CON VARCHAR(4000) NOT NULL, 
	USE_YN CHAR(1) NOT NULL, 
	RPMS_FRRG_EMN CHAR(6) NOT NULL, 
	RPMS_FRRG_TS TIMESTAMP NOT NULL, 
	RPMS_LSMD_EMN CHAR(6) NOT NULL, 
	RPMS_LSMD_TS TIMESTAMP NOT NULL, 
	CONSTRAINT PK_ICR_LDD010M PRIMARY KEY (CNBD_DSNC_ID) 
)


create table TB_ICR_LDP109M ( 
	DVCD CHAR(4) not null, 
	BSWR_ANLS_SQN INT(10) not null, 
	RMRK_CON VARCHAR(2000) not null, 
	RSNB_APND_FILE_ID VARCHAR(20) not null, 
	USE_YN CHAR(1) default 'Y', 
	RPMS_FRRG_EMN CHAR(6) not null, 
	RPMS_FRRG_TS TIMESTAMP not null, 
	RPMS_LSMD_EMN CHAR(6) not null, 
	RPMS_LSMD_TS TIMESTAMP not null, 
	constraint PK_ICR_LDP109M primary key (DVCD, BSWR_ANLS_SQN)
	)

create table TB_ICR_LDD012L ( 
	SBMS_PRHS_SQN INT(5) not null, 
	SBMS_YN CHAR(1) default 'N', 
	SBMS_TTL_NM VARCHAR(200) not null, 
	SBPL_NM VARCHAR(50) not null, 
	RMRK_CON VARCHAR(2000) not null, 
	BDDC_DCDE_YMD VARCHAR(8) not null, 
	DVCD CHAR(4) not null, 
	SBMS_YMD VARCHAR(8) not null, 
	SBMS_EMN CHAR(6) not null, 
	RSNB_APND_FILE_ID VARCHAR(20) not null, 
	RSNB_ETC_APND_FILE_ID VARCHAR(20) not null, 
	USE_YN CHAR(1) default 'Y', 
	RPMS_FRRG_EMN CHAR(6) not null, 
	RPMS_FRRG_TS TIMESTAMP not null, 
	RPMS_LSMD_EMN CHAR(6) not null, 
	RPMS_LSMD_TS TIMESTAMP not null, 
	constraint PK_ICR_LDD012H primary key (SBMS_PRHS_SQN) 
)


create table TB_ICR_LDD013M ( 
	MMBD_MNGM_ACVT_DSNC_ID VARCHAR(10) NOT NULL, 
	MNGM_ACVT_MNGN_CON VARCHAR(4000) NOT NULL, 
	MNGM_SCLT_SBJC_VL VARCHAR(2) NOT NULL, 
	USE_YN CHAR(1) NOT NULL, 
	RPMS_FRRG_EMN CHAR(6) NOT NULL, 
	RPMS_FRRG_TS TIMESTAMP NOT NULL, 
	RPMS_LSMD_EMN CHAR(6) NOT NULL, 
	RPMS_LSMD_TS TIMESTAMP NOT NULL, 
	CONSTRAINT PK_ICR_LDD013M PRIMARY KEY (MMBD_MNGM_ACVT_DSNC_ID)
)


create table TB_ICR_LDD014R ( 
	MMBD_RSPT_DSNC_ID VARCHAR(10) not null, 
	MMBD_MNGM_ACVT_DSNC_ID VARCHAR(10) not null, 
	USE_YN CHAR(1) not null, 
	RPMS_FRRG_EMN CHAR(6) not null, 
	RPMS_FRRG_TS TIMESTAMP not null, 
	RPMS_LSMD_EMN CHAR(6) not null, 
	RPMS_LSMD_TS TIMESTAMP not null, 
	constraint PK_ICR_LDD014R primary key (MMBD_RSPT_DSNC_ID, MMBD_MNGM_ACVT_DSNC_ID)
)

create table TB_ICR_LDD015R ( 
	MNGM_ACVT_DSNC_ID VARCHAR(10) NOT NULL, 
	MMBD_MNGM_ACVT_DSNC_ID VARCHAR(10) NOT NULL, 
	DVCD CHAR(4) NOT NULL, 
	USE_YN CHAR(1) NOT NULL, 
	RPMS_FRRG_EMN CHAR(6) NOT NULL, 
	RPMS_FRRG_TS TIMESTAMP NOT NULL, 
	RPMS_LSMD_EMN CHAR(6) NOT NULL, 
	RPMS_LSMD_TS TIMESTAMP NOT NULL, 
	CONSTRAINT PK_ICR_LDD015R PRIMARY KEY (MNGM_ACVT_DSNC_ID, MMBD_MNGM_ACVT_DSNC_ID) 
)

