CREATE TABLE `STOCK_CATEGORY_T` (
	`STOCK_CT_NO`	NUMBER	NOT NULL	COMMENT '카테고리번호',
	`STOCK_CT_NAME`	VARCHAR2(20)	NULL	COMMENT '카테고리명'
);

CREATE TABLE `CR_EMP_T` (
	`CHAT_ROOM_NO`	NUMBER	NOT NULL	COMMENT '방번호',
	`EMP_NO`	NUMBER	NOT NULL	COMMENT '참가자번호',
	`ENTRY_STAT`	NUMBER	NULL	COMMENT '0: 입장 / 1: 퇴장',
	`ALARM_STAT`	NUMBER	NULL	COMMENT '0: 켜기 / 1: 끄기'
);

CREATE TABLE `TIME_OFF_TEMP_T` (
	`TIME_OFF_TEMP_NO`	NUMBER	NOT NULL	COMMENT '휴가휴직임시번호',
	`TIME_OFF_CT_NO`	NUMBER	NULL	COMMENT '0: 휴가신청서 / 1: 휴직신청서',
	`TIME_OFF_START_DT`	DATE	NULL	COMMENT '시작일',
	`TIME_OFF_END_DT`	DATE	NULL	COMMENT '종료일',
	`TIME_OFF_PERIOD`	NUMBER	NULL	COMMENT '기간',
	`TIME_OFF_CONTENT`	VARCHAR2(200)	NULL	COMMENT '문서내용',
	`EMP_NO`	NUMBER	NOT NULL	COMMENT '직원번호'
);

CREATE TABLE `CHAT_MESSAGE_T` (
	`MSG_NO`	NUMBER	NOT NULL	COMMENT '메시지번호',
	`MSG_CONTENT`	VARCHAR2(1000)	NULL	COMMENT '메시지내용',
	`MSG_DT`	TIMESTAMP	NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '전송시간',
	`MSG_STAT`	NUMBER	NULL	DEFAULT 0	COMMENT '0: 활성화 / 1: 비활성화',
	`CREATE_DT`	TIMESTAMP	NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '생성일',
	`CREATOR`	NUMBER	NULL	COMMENT '생성자',
	`MODIFY_DT`	DATE	NULL	COMMENT '수정일',
	`MODIFIER`	NUMBER	NULL	COMMENT '수정자',
	`CHAT_ROOM_NO`	NUMBER	NOT NULL	COMMENT '방번호',
	`EMP_NO`	NUMBER	NOT NULL	COMMENT '직원번호'
);

CREATE TABLE `COMMENT_T` (
	`CMT_NO`	NUMBER	NOT NULL	COMMENT '댓글번호',
	`CMT_CONTENT`	VARCHAR2(1000)	NULL	COMMENT '댓글내용',
	`CMT_CREATE_DT`	DATE	NULL	DEFAULT CURRENT_DATE	COMMENT '작성일',
	`CMT_STAT`	NUMBER	NULL	DEFAULT 0	COMMENT '댓글 상태',
	`CREATE_DT`	DATE	NULL	DEFAULT CURRENT_DATE	COMMENT '생성일',
	`CREATOR`	NUMBER	NULL	COMMENT '생성자',
	`MODIFY_DT`	DATE	NULL	COMMENT '수정일',
	`MODIFIER`	NUMBER	NULL	COMMENT '수정자',
	`BOARD_NO`	NUMBER	NOT NULL	COMMENT '게시글번호',
	`PARENT_CMT_NO`	NUMBER	NULL	COMMENT '부모댓글번호'
);

CREATE TABLE `APPR_LINE_T` (
	`APPR_LINE_NO`	NUMBER	NOT NULL	COMMENT '결재선번호',
	`APPR_LINE_ORDER`	NUMBER	NULL	COMMENT '결재순서',
	`APPR_LINE_STAT`	NUMBER	NULL	DEFAULT 0	COMMENT '0: 대기 / 1: 승인 / 2: 반려',
	`APPR_LINE_DT`	DATE	NULL	DEFAULT CURRENT_DATE	COMMENT '결재일',
	`APPR_SIGN`	VARCHAR2(200)	NULL	COMMENT '결재서명',
	`APPR_LINE_REASON`	VARCHAR2(200)	NULL	COMMENT '반려사유',
	`CREATE_DT`	DATE	NULL	DEFAULT CURRENT_DATE	COMMENT '생성일',
	`CREATOR`	NUMBER	NULL	COMMENT '생성자',
	`MODIFY_DT`	DATE	NULL	COMMENT '수정일',
	`MODIFIER`	NUMBER	NULL	COMMENT '수정자',
	`APPR_NO`	NUMBER	NOT NULL	COMMENT '문서번호',
	`EMP_NO`	NUMBER	NULL	COMMENT '직원번호'
);

CREATE TABLE `ENTRY_EXIT_T` (
	`CHAT_ROOM_NO`	NUMBER	NOT NULL	COMMENT '방번호',
	`EMP_NO`	NUMBER	NOT NULL	COMMENT '참가자번호',
	`ENTRY_DT`	TIMESTAMP	NULL	COMMENT '입장일',
	`EXIT_DT`	TIMESTAMP	NULL	COMMENT '퇴장일'
);

CREATE TABLE `ADMIN_T` (
	`ADMIN_NO`	NUMBER	NOT NULL	COMMENT '관리자번호',
	`ADMIN_ID`	VARCHAR2(20)	NOT NULL	COMMENT '아이디',
	`ADMIN_PW`	VARCHAR2(150)	NOT NULL	COMMENT '비밀번호',
	`ADMIN_SIGN`	VARCHAR2(200)	NULL	COMMENT '결재서명',
	`REFRESH_TOKEN`	VARCHAR2(255)	NULL	COMMENT '리프레시토큰'
);

CREATE TABLE `NOTIFICATION_T` (
	`NOTIFY_NO`	NUMBER	NOT NULL	COMMENT '알림번호',
	`NOTIFY_CT`	NUMBER	NULL	COMMENT '0: 발주 / 1: 휴가 / 2: 휴직 / 3: 승인 / 4: 반려',
	`NOTIFY_CONTENT`	VARCHAR2(100)	NULL	COMMENT '알림내용',
	`EMP_NO`	NUMBER	NULL	COMMENT '직원번호',
	`TIME_OFF_TYPE`	VARCHAR2(20)	NULL	COMMENT '직원분류',
	`APPR_TYPE`	VARCHAR2(20)	NULL	COMMENT '결재분류',
	`DOCUMENT_TYPE`	VARCHAR2(20)	NULL	COMMENT '문서분류',
	`NOTIFY_STAT`	NUMBER	NULL	DEFAULT 0	COMMENT '0: 읽지 않음 / 1: 읽음',
	`CREATE_DT`	DATE	NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '생성일',
	`CREATOR`	NUMBER	NULL	COMMENT '생성자',
	`MODIFY_DT`	DATE	NULL	COMMENT '수정일',
	`MODIFIER`	NUMBER	NULL	COMMENT '수정자'
);

CREATE TABLE `VERIFICATION_T` (
	`VERIFY_NO`	VARCHAR2(50)	NOT NULL	COMMENT '인증기록번호',
	`VERIFY_EMAIL`	VARCHAR2(50)	NOT NULL	COMMENT '이메일',
	`VERIFY_CODE`	VARCHAR2(20)	NOT NULL	COMMENT '인증코드',
	`VERIFY_END_DT`	DATE	NOT NULL	DEFAULT CURRENT_DATE + (INTERVAL '5' MINUTE)	COMMENT '만료시간',
	`VERIFY_STAT`	NUMBER	NULL	COMMENT '0: 유효 / 1: 사용 / 2: 만료'
);

CREATE TABLE `SALES_T` (
	`SAL_NO`	NUMBER	NOT NULL	COMMENT '매출번호',
	`SAL_DT`	DATE	NULL	DEFAULT CURRENT_DATE	COMMENT '매출일',
	`SAL_PRICE`	NUMBER	NULL	COMMENT '매출액',
	`CREATE_DT`	DATE	NULL	DEFAULT CURRENT_DATE	COMMENT '생성일',
	`CREATOR`	NUMBER	NULL	COMMENT '생성자',
	`MODIFY_DT`	DATE	NULL	COMMENT '수정일',
	`MODIFIER`	NUMBER	NULL	COMMENT '수정자',
	`FRN_NO`	NUMBER	NULL	COMMENT '가맹점번호'
);

CREATE TABLE `STOCK_ORDER_TEMP_T` (
	`ORDER_TEMP_NO`	NUMBER	NOT NULL	COMMENT '발주임시번호',
	`STOCK_NO`	NUMBER	NOT NULL	COMMENT '재고번호',
	`STOCK_ORDER_COUNT`	NUMBER	NULL	COMMENT '수량',
	`STOCK_ORDER_COST`	NUMBER	NULL	COMMENT '금액',
	`EMP_NO`	NUMBER	NOT NULL	COMMENT '직원번호'
);

CREATE TABLE `TIME_OFF_T` (
	`APPR_NO`	NUMBER	NOT NULL	COMMENT '문서번호',
	`TIME_OFF_CT_NO`	NUMBER	NULL	COMMENT '0: 휴가신청서 / 1: 휴직신청서',
	`TIME_OFF_START_DT`	DATE	NULL	COMMENT '시작일',
	`TIME_OFF_END_DT`	DATE	NULL	COMMENT '종료일',
	`TIME_OFF_PERIOD`	NUMBER	NULL	COMMENT '기간',
	`TIME_OFF_CONTENT`	VARCHAR2(200)	NULL	COMMENT '문서내용'
);

CREATE TABLE `POSITION_T` (
	`POS_NO`	NUMBER	NOT NULL	COMMENT '0: 점주 / 1: 매니저 / 2: 직원',
	`POS_NAME`	VARCHAR2(50)	NULL	COMMENT '직책명'
);

CREATE TABLE `BOARD_LIKE_T` (
	`BOARD_NO`	NUMBER	NOT NULL	COMMENT '게시글번호',
	`EMP_NO`	NUMBER	NOT NULL	COMMENT '직원번호'
);

CREATE TABLE `BOARD_FILE_T` (
	`BOARD_FILE_NO`	NUMBER	NOT NULL	COMMENT '첨부파일번호',
	`BOARD_ORIGIN`	VARCHAR2(200)	NULL	COMMENT '첨부파일원본명',
	`BOARD_RENAME`	VARCHAR2(200)	NULL	COMMENT '첨부파일변경명',
	`BOARD_PATH`	VARCHAR2(200)	NULL	COMMENT '첨부파일경로',
	`BOARD_NO`	NUMBER	NOT NULL	COMMENT '게시글번호'
);

CREATE TABLE `INVENTORY_STAT_T` (
	`IS_NO`	NUMBER	NOT NULL	COMMENT '재고현황번호',
	`IS_COUNT`	NUMBER	NULL	COMMENT '재고수량',
	`STOCK_NO`	NUMBER	NOT NULL	COMMENT '재고번호',
	`FRN_NO`	NUMBER	NULL	COMMENT '가맹점번호'
);

CREATE TABLE `STOCK_ORDER_T` (
	`APPR_NO`	NUMBER	NOT NULL	COMMENT '문서번호',
	`STOCK_NO`	NUMBER	NOT NULL	COMMENT '재고번호',
	`STOCK_ORDER_COUNT`	NUMBER	NULL	COMMENT '수량',
	`STOCK_ORDER_COST`	NUMBER	NULL	COMMENT '금액'
);

CREATE TABLE `ANNUAL_T` (
	`ANN_NO`	NUMBER	NOT NULL	COMMENT '연차번호',
	`ANN_ID`	VARCHAR2(50)	NOT NULL	COMMENT '연차아이디',
	`ANN_CT_NO`	NUMBER	NULL	COMMENT '0: 연차 / 1: 반차 / 2: 반반차',
	`ANN_TITLE`	VARCHAR2(50)	NULL	COMMENT '연차제목',
	`ANN_CONTENT`	VARCHAR2(100)	NULL	COMMENT '연차내용',
	`ANN_TOTAL`	NUMBER	NULL	DEFAULT 15	COMMENT '연차일수',
	`ANN_START_TIME`	VARCHAR2(50)	NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '시작일',
	`ANN_END_TIME`	VARCHAR2(50)	NULL	COMMENT '종료일',
	`CREATE_DT`	DATE	NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '생성일',
	`CREATOR`	NUMBER	NULL	COMMENT '생성자',
	`MODIFY_DT`	DATE	NULL	COMMENT '수정일',
	`MODIFIER`	NUMBER	NULL	COMMENT '수정자',
	`EMP_NO`	NUMBER	NOT NULL	COMMENT '직원번호'
);

CREATE TABLE `ORDER_T` (
	`APPR_NO`	NUMBER	NOT NULL	COMMENT '문서번호',
	`ORDER_COST`	NUMBER	NULL	COMMENT '합계금액'
);

CREATE TABLE `APPR_FILE_T` (
	`APPR_FILE_NO`	NUMBER	NOT NULL	COMMENT '첨부파일번호',
	`APPR_ORIGIN`	VARCHAR2(200)	NULL	COMMENT '첨부파일원본명',
	`APPR_RENAME`	VARCHAR2(200)	NULL	COMMENT '첨부파일변경명',
	`APPR_PATH`	VARCHAR2(200)	NULL	COMMENT '첨부파일경로',
	`APPR_NO`	NUMBER	NOT NULL	COMMENT '문서번호'
);

CREATE TABLE `ATTENDANCE_T` (
	`ATT_NO`	NUMBER	NOT NULL	COMMENT '근태번호',
	`ATT_IN_TIME`	VARCHAR2(50)	NULL	COMMENT '출근시간',
	`ATT_OUT_TIME`	VARCHAR2(50)	NULL	COMMENT '퇴근시간',
	`ATT_WORK_TIME`	VARCHAR2(50)	NULL	COMMENT '근무시간',
	`CREATE_DT`	DATE	NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '생성일',
	`CREATOR`	NUMBER	NULL	COMMENT '생성자',
	`MODIFY_DT`	DATE	NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '수정일',
	`MODIFIER`	NUMBER	NULL	COMMENT '수정자',
	`EMP_NO`	NUMBER	NOT NULL	COMMENT '직원번호'
);

CREATE TABLE `FRANCHISE_T` (
	`FRN_NO`	NUMBER	NOT NULL	COMMENT '가맹점번호',
	`FRN_NAME`	VARCHAR2(50)	NULL	COMMENT '가맹점명',
	`FRN_OWNER`	VARCHAR2(50)	NULL	COMMENT '대표자',
	`FRN_TEL`	VARCHAR2(20)	NULL	COMMENT '전화번호',
	`FRN_ZIP`	VARCHAR2(5)	NULL	COMMENT '우편번호',
	`FRN_STREET`	VARCHAR2(100)	NULL	COMMENT '도로명주소',
	`FRN_DETAIL`	VARCHAR2(100)	NULL	COMMENT '상세주소',
	`FRN_GU`	VARCHAR2(20)	NULL	COMMENT '구 이름',
	`FRN_X`	VARCHAR2(50)	NULL	COMMENT '위도',
	`FRN_Y`	VARCHAR2(50)	NULL	COMMENT '경도',
	`FRN_START_TIME`	VARCHAR2(50)	NULL	COMMENT '운영시작시간',
	`FRN_END_TIME`	VARCHAR2(50)	NULL	COMMENT '운영종료시간',
	`FRN_IMG`	VARCHAR2(200)	NULL	COMMENT '가맹점이미지',
	`FRN_JOIN_DT`	DATE	NULL	DEFAULT CURRENT_DATE	COMMENT '가맹일',
	`CREATE_DT`	DATE	NULL	DEFAULT CURRENT_DATE	COMMENT '생성일',
	`CREATOR`	NUMBER	NULL	COMMENT '생성자',
	`MODIFY_DT`	DATE	NULL	COMMENT '수정일',
	`MODIFIER`	NUMBER	NULL	COMMENT '수정자'
);

CREATE TABLE `EMPLOYEE_T` (
	`EMP_NO`	NUMBER	NOT NULL	COMMENT '직원번호',
	`EMP_ID`	VARCHAR2(20)	NOT NULL	COMMENT '아이디',
	`EMP_PW`	VARCHAR2(150)	NOT NULL	COMMENT '비밀번호',
	`EMP_NAME`	VARCHAR2(50)	NOT NULL	COMMENT '직원명',
	`EMP_EMAIL`	VARCHAR2(50)	NULL	COMMENT '이메일',
	`EMP_PHONE`	VARCHAR2(20)	NULL	COMMENT '휴대폰',
	`EMP_ZIP`	VARCHAR2(5)	NULL	COMMENT '우편번호',
	`EMP_STREET`	VARCHAR2(100)	NULL	COMMENT '도로명주소',
	`EMP_DETAIL`	VARCHAR2(100)	NULL	COMMENT '상세주소',
	`EMP_PROFILE`	VARCHAR2(200)	NULL	COMMENT '프로필이미지',
	`EMP_SIGN`	VARCHAR2(200)	NULL	COMMENT '결재서명',
	`EMP_ANNUAL`	NUMBER	NULL	DEFAULT 15	COMMENT '연차일수',
	`EMP_STAT`	NUMBER	NULL	COMMENT '0: 재직 / 1: 휴직 / 2: 퇴직',
	`EMP_IN_DT`	DATE	NULL	COMMENT '입사일',
	`EMP_OUT_DT`	DATE	NULL	COMMENT '퇴사일',
	`CREATE_DT`	DATE	NULL	DEFAULT CURRENT_DATE	COMMENT '생성일',
	`CREATOR`	NUMBER	NULL	COMMENT '생성자',
	`MODIFY_DT`	DATE	NULL	COMMENT '수정일',
	`MODIFIER`	NUMBER	NULL	COMMENT '수정자',
	`REFRESH_TOKEN`	VARCHAR2(255)	NULL	COMMENT '리프레시토큰',
	`FRN_NO`	NUMBER	NULL	COMMENT '가맹점번호',
	`POS_NO`	NUMBER	NOT NULL	COMMENT '직책번호'
);

CREATE TABLE `SCHEDULE_T` (
	`SCHE_NO`	NUMBER	NOT NULL	COMMENT '일정번호',
	`SCHE_ID`	VARCHAR2(50)	NOT NULL	COMMENT '일정아이디',
	`FRN_NO`	NUMBER	NULL	COMMENT '가맹점번호',
	`SCHE_DIV`	NUMBER	NULL	COMMENT '0: 공개 / 1: 개인',
	`SCHE_TITLE`	VARCHAR2(50)	NULL	COMMENT '일정제목',
	`SCHE_CONTENT`	VARCHAR2(100)	NULL	COMMENT '일정내용',
	`SCHE_START_TIME`	VARCHAR2(50)	NULL	COMMENT '시작일',
	`SCHE_END_TIME`	VARCHAR2(50)	NULL	COMMENT '종료일',
	`SCHE_STAT`	NUMBER	NULL	COMMENT '0: 미진행 / 1: 만료,삭제',
	`CREATE_DT`	DATE	NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '생성일',
	`CREATOR`	NUMBER	NULL	COMMENT '생성자',
	`MODIFY_DT`	DATE	NULL	COMMENT '수정일',
	`MODIFIER`	NUMBER	NULL	COMMENT '수정자',
	`EMP_NO`	NUMBER	NOT NULL	COMMENT '직원번호'
);

CREATE TABLE `STOCK_T` (
	`STOCK_NO`	NUMBER	NOT NULL	COMMENT '재고번호',
	`STOCK_NAME`	VARCHAR2(50)	NULL	COMMENT '재고명',
	`STOCK_IMG`	VARCHAR2(200)	NULL	COMMENT '재고이미지',
	`STOCK_DETAIL`	VARCHAR2(1000)	NULL	COMMENT '재고설명',
	`STOCK_UNIT`	VARCHAR2(10)	NULL	COMMENT '재고단위',
	`STOCK_PRICE`	NUMBER	NULL	COMMENT '재고단가',
	`STOCK_CT_NO`	NUMBER	NOT NULL	COMMENT '카테고리번호'
);

CREATE TABLE `APPROVAL_T` (
	`APPR_NO`	NUMBER	NOT NULL	COMMENT '문서번호',
	`APPR_DT`	DATE	NULL	DEFAULT CURRENT_DATE	COMMENT '기안일',
	`APPR_STAT`	NUMBER	NULL	DEFAULT 0	COMMENT '0: 대기 / 1: 진행중 / 2: 승인 / 3: 반려',
	`CREATE_DT`	DATE	NULL	DEFAULT CURRENT_DATE	COMMENT '생성일',
	`CREATOR`	NUMBER	NULL	COMMENT '생성자',
	`MODIFY_DT`	DATE	NULL	COMMENT '수정일',
	`MODIFIER`	NUMBER	NULL	COMMENT '수정자',
	`EMP_NO`	NUMBER	NOT NULL	COMMENT '직원번호'
);

CREATE TABLE `CHAT_ROOM_T` (
	`CHAT_ROOM_NO`	NUMBER	NOT NULL	COMMENT '방번호',
	`CHAT_ROOM_TITLE`	VARCHAR2(50)	NULL	COMMENT '채팅방제목',
	`CHAT_ROOM_STAT`	NUMBER	NULL	DEFAULT 0	COMMENT '0: 활성화 / 1: 비활성화',
	`CREATE_DT`	TIMESTAMP	NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '생성일',
	`CREATOR`	NUMBER	NULL	COMMENT '생성자',
	`MODIFY_DT`	DATE	NULL	COMMENT '수정일',
	`MODIFIER`	NUMBER	NULL	COMMENT '수정자'
);

CREATE TABLE `BOARD_T` (
	`BOARD_NO`	NUMBER	NOT NULL	COMMENT '게시글번호',
	`BOARD_CT_NO`	NUMBER	NULL	COMMENT '0: 공지사항 / 1: 자유게시판',
	`BOARD_TITLE`	VARCHAR2(100)	NULL	COMMENT '게시글제목',
	`BOARD_CONTENT`	CLOB	NULL	COMMENT '게시글내용',
	`BOARD_HIT`	NUMBER	NULL	DEFAULT 0	COMMENT '조회수',
	`BOARD_LIKE_COUNT`	NUMBER	NULL	DEFAULT 0	COMMENT '좋아요 개수',
	`BOARD_STAT`	NUMBER	NULL	DEFAULT 0	COMMENT '게시글 상태',
	`CREATE_DT`	DATE	NULL	DEFAULT CURRENT_DATE	COMMENT '생성일',
	`CREATOR`	NUMBER	NULL	COMMENT '작성자',
	`MODIFY_DT`	DATE	NULL	COMMENT '수정일',
	`MODIFIER`	NUMBER	NULL	COMMENT '수정자',
	`EMP_NO`	NUMBER	NULL	COMMENT '직원번호'
);

CREATE TABLE `CR_ACCESS_T` (
	`CHAT_ROOM_NO`	NUMBER	NOT NULL	COMMENT '방번호',
	`EMP_NO`	NUMBER	NOT NULL	COMMENT '직원번호',
	`ACCESS_DT`	TIMESTAMP	NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '접속시간'
);

